language: ruby

services:
  - redis-server
rvm:
  - 1.9.3
  
env:
  - "TEST_DB=14"
before_script:
  - mkdir -p shippable/testresults
# write the rspec tests to the output dir
script:
  - rspec spec/base_spec.rb -o shippable/testresults/results.xml
